# Generated by Django 5.0.4 on 2024-04-20 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todos',
            old_name='unique_id',
            new_name='todo_id',
        ),
    ]
